<?php
/**
 * CarrierInfoApi
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Shipping API
 *
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use OpenAPI\Client\ApiException;
use OpenAPI\Client\Configuration;
use OpenAPI\Client\HeaderSelector;
use OpenAPI\Client\ObjectSerializer;

/**
 * CarrierInfoApi Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CarrierInfoApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $host_index (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $host_index = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $host_index;
    }

    /**
     * Set the host index
     *
     * @param  int Host index (required)
     */
    public function setHostIndex($host_index)
    {
        $this->hostIndex = $host_index;
    }

    /**
     * Get the host index
     *
     * @return Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation v1CarrierFacilityPost
     *
     * Find Carrier Facilities
     *
     * @param  \OpenAPI\Client\Model\CarrierFacilityRequest $carrier_facility_request carrier_facility_request (required)
     * @param  string $x_pb_unified_error_structure Set this to true to use the standard [error object](https://shipping.pitneybowes.com/reference/error-object.html#standard-error-object) if an error occurs. (optional, default to 'true')
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\CarrierFacilityResponse|\OpenAPI\Client\Model\CrossBorderQuotesErrors
     */
    public function v1CarrierFacilityPost($carrier_facility_request, $x_pb_unified_error_structure = 'true')
    {
        list($response) = $this->v1CarrierFacilityPostWithHttpInfo($carrier_facility_request, $x_pb_unified_error_structure);
        return $response;
    }

    /**
     * Operation v1CarrierFacilityPostWithHttpInfo
     *
     * Find Carrier Facilities
     *
     * @param  \OpenAPI\Client\Model\CarrierFacilityRequest $carrier_facility_request (required)
     * @param  string $x_pb_unified_error_structure Set this to true to use the standard [error object](https://shipping.pitneybowes.com/reference/error-object.html#standard-error-object) if an error occurs. (optional, default to 'true')
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\CarrierFacilityResponse|\OpenAPI\Client\Model\CrossBorderQuotesErrors, HTTP status code, HTTP response headers (array of strings)
     */
    public function v1CarrierFacilityPostWithHttpInfo($carrier_facility_request, $x_pb_unified_error_structure = 'true')
    {
        $request = $this->v1CarrierFacilityPostRequest($carrier_facility_request, $x_pb_unified_error_structure);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            switch($statusCode) {
                case 200:
                    if ('\OpenAPI\Client\Model\CarrierFacilityResponse' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\CarrierFacilityResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                default:
                    if ('\OpenAPI\Client\Model\CrossBorderQuotesErrors' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\CrossBorderQuotesErrors', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\OpenAPI\Client\Model\CarrierFacilityResponse';
            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = (string) $responseBody;
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\CarrierFacilityResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\CrossBorderQuotesErrors',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation v1CarrierFacilityPostAsync
     *
     * Find Carrier Facilities
     *
     * @param  \OpenAPI\Client\Model\CarrierFacilityRequest $carrier_facility_request (required)
     * @param  string $x_pb_unified_error_structure Set this to true to use the standard [error object](https://shipping.pitneybowes.com/reference/error-object.html#standard-error-object) if an error occurs. (optional, default to 'true')
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1CarrierFacilityPostAsync($carrier_facility_request, $x_pb_unified_error_structure = 'true')
    {
        return $this->v1CarrierFacilityPostAsyncWithHttpInfo($carrier_facility_request, $x_pb_unified_error_structure)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v1CarrierFacilityPostAsyncWithHttpInfo
     *
     * Find Carrier Facilities
     *
     * @param  \OpenAPI\Client\Model\CarrierFacilityRequest $carrier_facility_request (required)
     * @param  string $x_pb_unified_error_structure Set this to true to use the standard [error object](https://shipping.pitneybowes.com/reference/error-object.html#standard-error-object) if an error occurs. (optional, default to 'true')
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1CarrierFacilityPostAsyncWithHttpInfo($carrier_facility_request, $x_pb_unified_error_structure = 'true')
    {
        $returnType = '\OpenAPI\Client\Model\CarrierFacilityResponse';
        $request = $this->v1CarrierFacilityPostRequest($carrier_facility_request, $x_pb_unified_error_structure);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v1CarrierFacilityPost'
     *
     * @param  \OpenAPI\Client\Model\CarrierFacilityRequest $carrier_facility_request (required)
     * @param  string $x_pb_unified_error_structure Set this to true to use the standard [error object](https://shipping.pitneybowes.com/reference/error-object.html#standard-error-object) if an error occurs. (optional, default to 'true')
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function v1CarrierFacilityPostRequest($carrier_facility_request, $x_pb_unified_error_structure = 'true')
    {
        // verify the required parameter 'carrier_facility_request' is set
        if ($carrier_facility_request === null || (is_array($carrier_facility_request) && count($carrier_facility_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $carrier_facility_request when calling v1CarrierFacilityPost'
            );
        }

        $resourcePath = '/v1/carrier-facility';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($x_pb_unified_error_structure !== null) {
            $headerParams['X-PB-UnifiedErrorStructure'] = ObjectSerializer::toHeaderValue($x_pb_unified_error_structure);
        }


        // body params
        $_tempBody = null;
        if (isset($carrier_facility_request)) {
            $_tempBody = $carrier_facility_request;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($_tempBody));
            } else {
                $httpBody = $_tempBody;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation v1CarrierLicenseAgreementsGet
     *
     * This operation retrieves a carrier's license agreement.
     *
     * @param  string $accept_language This HTTP header advertises which languages the client is able to understand, and which locale variant is preferred. (required)
     * @param  string $carrier The carrier name. Currently this must be set to: UPS (required)
     * @param  \OpenAPI\Client\Model\ISOCountryCode $origin_country_code The two-character ISO country code for the country where the shipment originates. (required)
     * @param  string $x_pb_unified_error_structure Set this to true to use the standard [error object](https://shipping.pitneybowes.com/reference/error-object.html#standard-error-object) if an error occurs. (optional, default to 'true')
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\InlineResponse200|\OpenAPI\Client\Model\Errors
     */
    public function v1CarrierLicenseAgreementsGet($accept_language, $carrier, $origin_country_code, $x_pb_unified_error_structure = 'true')
    {
        list($response) = $this->v1CarrierLicenseAgreementsGetWithHttpInfo($accept_language, $carrier, $origin_country_code, $x_pb_unified_error_structure);
        return $response;
    }

    /**
     * Operation v1CarrierLicenseAgreementsGetWithHttpInfo
     *
     * This operation retrieves a carrier's license agreement.
     *
     * @param  string $accept_language This HTTP header advertises which languages the client is able to understand, and which locale variant is preferred. (required)
     * @param  string $carrier The carrier name. Currently this must be set to: UPS (required)
     * @param  \OpenAPI\Client\Model\ISOCountryCode $origin_country_code The two-character ISO country code for the country where the shipment originates. (required)
     * @param  string $x_pb_unified_error_structure Set this to true to use the standard [error object](https://shipping.pitneybowes.com/reference/error-object.html#standard-error-object) if an error occurs. (optional, default to 'true')
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\InlineResponse200|\OpenAPI\Client\Model\Errors, HTTP status code, HTTP response headers (array of strings)
     */
    public function v1CarrierLicenseAgreementsGetWithHttpInfo($accept_language, $carrier, $origin_country_code, $x_pb_unified_error_structure = 'true')
    {
        $request = $this->v1CarrierLicenseAgreementsGetRequest($accept_language, $carrier, $origin_country_code, $x_pb_unified_error_structure);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            switch($statusCode) {
                case 200:
                    if ('\OpenAPI\Client\Model\InlineResponse200' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\InlineResponse200', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                default:
                    if ('\OpenAPI\Client\Model\Errors' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\Errors', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\OpenAPI\Client\Model\InlineResponse200';
            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = (string) $responseBody;
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\InlineResponse200',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\Errors',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation v1CarrierLicenseAgreementsGetAsync
     *
     * This operation retrieves a carrier's license agreement.
     *
     * @param  string $accept_language This HTTP header advertises which languages the client is able to understand, and which locale variant is preferred. (required)
     * @param  string $carrier The carrier name. Currently this must be set to: UPS (required)
     * @param  \OpenAPI\Client\Model\ISOCountryCode $origin_country_code The two-character ISO country code for the country where the shipment originates. (required)
     * @param  string $x_pb_unified_error_structure Set this to true to use the standard [error object](https://shipping.pitneybowes.com/reference/error-object.html#standard-error-object) if an error occurs. (optional, default to 'true')
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1CarrierLicenseAgreementsGetAsync($accept_language, $carrier, $origin_country_code, $x_pb_unified_error_structure = 'true')
    {
        return $this->v1CarrierLicenseAgreementsGetAsyncWithHttpInfo($accept_language, $carrier, $origin_country_code, $x_pb_unified_error_structure)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v1CarrierLicenseAgreementsGetAsyncWithHttpInfo
     *
     * This operation retrieves a carrier's license agreement.
     *
     * @param  string $accept_language This HTTP header advertises which languages the client is able to understand, and which locale variant is preferred. (required)
     * @param  string $carrier The carrier name. Currently this must be set to: UPS (required)
     * @param  \OpenAPI\Client\Model\ISOCountryCode $origin_country_code The two-character ISO country code for the country where the shipment originates. (required)
     * @param  string $x_pb_unified_error_structure Set this to true to use the standard [error object](https://shipping.pitneybowes.com/reference/error-object.html#standard-error-object) if an error occurs. (optional, default to 'true')
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1CarrierLicenseAgreementsGetAsyncWithHttpInfo($accept_language, $carrier, $origin_country_code, $x_pb_unified_error_structure = 'true')
    {
        $returnType = '\OpenAPI\Client\Model\InlineResponse200';
        $request = $this->v1CarrierLicenseAgreementsGetRequest($accept_language, $carrier, $origin_country_code, $x_pb_unified_error_structure);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v1CarrierLicenseAgreementsGet'
     *
     * @param  string $accept_language This HTTP header advertises which languages the client is able to understand, and which locale variant is preferred. (required)
     * @param  string $carrier The carrier name. Currently this must be set to: UPS (required)
     * @param  \OpenAPI\Client\Model\ISOCountryCode $origin_country_code The two-character ISO country code for the country where the shipment originates. (required)
     * @param  string $x_pb_unified_error_structure Set this to true to use the standard [error object](https://shipping.pitneybowes.com/reference/error-object.html#standard-error-object) if an error occurs. (optional, default to 'true')
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function v1CarrierLicenseAgreementsGetRequest($accept_language, $carrier, $origin_country_code, $x_pb_unified_error_structure = 'true')
    {
        // verify the required parameter 'accept_language' is set
        if ($accept_language === null || (is_array($accept_language) && count($accept_language) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $accept_language when calling v1CarrierLicenseAgreementsGet'
            );
        }
        // verify the required parameter 'carrier' is set
        if ($carrier === null || (is_array($carrier) && count($carrier) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $carrier when calling v1CarrierLicenseAgreementsGet'
            );
        }
        // verify the required parameter 'origin_country_code' is set
        if ($origin_country_code === null || (is_array($origin_country_code) && count($origin_country_code) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $origin_country_code when calling v1CarrierLicenseAgreementsGet'
            );
        }

        $resourcePath = '/v1/carrier/license-agreements';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($carrier !== null) {
            if('form' === 'form' && is_array($carrier)) {
                foreach($carrier as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['carrier'] = $carrier;
            }
        }
        // query params
        if ($origin_country_code !== null) {
            if('form' === 'form' && is_array($origin_country_code)) {
                foreach($origin_country_code as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['originCountryCode'] = $origin_country_code;
            }
        }

        // header params
        if ($accept_language !== null) {
            $headerParams['Accept-Language'] = ObjectSerializer::toHeaderValue($accept_language);
        }
        // header params
        if ($x_pb_unified_error_structure !== null) {
            $headerParams['X-PB-UnifiedErrorStructure'] = ObjectSerializer::toHeaderValue($x_pb_unified_error_structure);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($_tempBody));
            } else {
                $httpBody = $_tempBody;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation v1CountriesGet
     *
     * This operation returns a list of supported destination countries to which the carrier offers international shipping services.
     *
     * @param  string $accept_language This HTTP header advertises which languages the client is able to understand, and which locale variant is preferred. (required)
     * @param  \OpenAPI\Client\Model\Carrier $carrier The carrier name. Currently this must be set to: USPS (required)
     * @param  \OpenAPI\Client\Model\ISOCountryCode $origin_country_code The two-character ISO country code for the country where the shipment originates. (required)
     * @param  string $x_pb_unified_error_structure Set this to true to use the standard [error object](https://shipping.pitneybowes.com/reference/error-object.html#standard-error-object) if an error occurs. (optional, default to 'true')
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return object[]|\OpenAPI\Client\Model\Errors
     */
    public function v1CountriesGet($accept_language, $carrier, $origin_country_code, $x_pb_unified_error_structure = 'true')
    {
        list($response) = $this->v1CountriesGetWithHttpInfo($accept_language, $carrier, $origin_country_code, $x_pb_unified_error_structure);
        return $response;
    }

    /**
     * Operation v1CountriesGetWithHttpInfo
     *
     * This operation returns a list of supported destination countries to which the carrier offers international shipping services.
     *
     * @param  string $accept_language This HTTP header advertises which languages the client is able to understand, and which locale variant is preferred. (required)
     * @param  \OpenAPI\Client\Model\Carrier $carrier The carrier name. Currently this must be set to: USPS (required)
     * @param  \OpenAPI\Client\Model\ISOCountryCode $origin_country_code The two-character ISO country code for the country where the shipment originates. (required)
     * @param  string $x_pb_unified_error_structure Set this to true to use the standard [error object](https://shipping.pitneybowes.com/reference/error-object.html#standard-error-object) if an error occurs. (optional, default to 'true')
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of object[]|\OpenAPI\Client\Model\Errors, HTTP status code, HTTP response headers (array of strings)
     */
    public function v1CountriesGetWithHttpInfo($accept_language, $carrier, $origin_country_code, $x_pb_unified_error_structure = 'true')
    {
        $request = $this->v1CountriesGetRequest($accept_language, $carrier, $origin_country_code, $x_pb_unified_error_structure);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            switch($statusCode) {
                case 200:
                    if ('object[]' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, 'object[]', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                default:
                    if ('\OpenAPI\Client\Model\Errors' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\Errors', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = 'object[]';
            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = (string) $responseBody;
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'object[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\Errors',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation v1CountriesGetAsync
     *
     * This operation returns a list of supported destination countries to which the carrier offers international shipping services.
     *
     * @param  string $accept_language This HTTP header advertises which languages the client is able to understand, and which locale variant is preferred. (required)
     * @param  \OpenAPI\Client\Model\Carrier $carrier The carrier name. Currently this must be set to: USPS (required)
     * @param  \OpenAPI\Client\Model\ISOCountryCode $origin_country_code The two-character ISO country code for the country where the shipment originates. (required)
     * @param  string $x_pb_unified_error_structure Set this to true to use the standard [error object](https://shipping.pitneybowes.com/reference/error-object.html#standard-error-object) if an error occurs. (optional, default to 'true')
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1CountriesGetAsync($accept_language, $carrier, $origin_country_code, $x_pb_unified_error_structure = 'true')
    {
        return $this->v1CountriesGetAsyncWithHttpInfo($accept_language, $carrier, $origin_country_code, $x_pb_unified_error_structure)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v1CountriesGetAsyncWithHttpInfo
     *
     * This operation returns a list of supported destination countries to which the carrier offers international shipping services.
     *
     * @param  string $accept_language This HTTP header advertises which languages the client is able to understand, and which locale variant is preferred. (required)
     * @param  \OpenAPI\Client\Model\Carrier $carrier The carrier name. Currently this must be set to: USPS (required)
     * @param  \OpenAPI\Client\Model\ISOCountryCode $origin_country_code The two-character ISO country code for the country where the shipment originates. (required)
     * @param  string $x_pb_unified_error_structure Set this to true to use the standard [error object](https://shipping.pitneybowes.com/reference/error-object.html#standard-error-object) if an error occurs. (optional, default to 'true')
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1CountriesGetAsyncWithHttpInfo($accept_language, $carrier, $origin_country_code, $x_pb_unified_error_structure = 'true')
    {
        $returnType = 'object[]';
        $request = $this->v1CountriesGetRequest($accept_language, $carrier, $origin_country_code, $x_pb_unified_error_structure);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v1CountriesGet'
     *
     * @param  string $accept_language This HTTP header advertises which languages the client is able to understand, and which locale variant is preferred. (required)
     * @param  \OpenAPI\Client\Model\Carrier $carrier The carrier name. Currently this must be set to: USPS (required)
     * @param  \OpenAPI\Client\Model\ISOCountryCode $origin_country_code The two-character ISO country code for the country where the shipment originates. (required)
     * @param  string $x_pb_unified_error_structure Set this to true to use the standard [error object](https://shipping.pitneybowes.com/reference/error-object.html#standard-error-object) if an error occurs. (optional, default to 'true')
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function v1CountriesGetRequest($accept_language, $carrier, $origin_country_code, $x_pb_unified_error_structure = 'true')
    {
        // verify the required parameter 'accept_language' is set
        if ($accept_language === null || (is_array($accept_language) && count($accept_language) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $accept_language when calling v1CountriesGet'
            );
        }
        // verify the required parameter 'carrier' is set
        if ($carrier === null || (is_array($carrier) && count($carrier) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $carrier when calling v1CountriesGet'
            );
        }
        // verify the required parameter 'origin_country_code' is set
        if ($origin_country_code === null || (is_array($origin_country_code) && count($origin_country_code) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $origin_country_code when calling v1CountriesGet'
            );
        }

        $resourcePath = '/v1/countries';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($carrier !== null) {
            if('form' === 'form' && is_array($carrier)) {
                foreach($carrier as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['carrier'] = $carrier;
            }
        }
        // query params
        if ($origin_country_code !== null) {
            if('form' === 'form' && is_array($origin_country_code)) {
                foreach($origin_country_code as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['originCountryCode'] = $origin_country_code;
            }
        }

        // header params
        if ($accept_language !== null) {
            $headerParams['Accept-Language'] = ObjectSerializer::toHeaderValue($accept_language);
        }
        // header params
        if ($x_pb_unified_error_structure !== null) {
            $headerParams['X-PB-UnifiedErrorStructure'] = ObjectSerializer::toHeaderValue($x_pb_unified_error_structure);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($_tempBody));
            } else {
                $httpBody = $_tempBody;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation v1InformationRulesRatingServicesGet
     *
     * Retrieves the rules governing the carrier's services.
     *
     * @param  string $accept_language This HTTP header advertises which languages the client is able to understand, and which locale variant is preferred. (required)
     * @param  \OpenAPI\Client\Model\Carrier $carrier The carrier name. **Currently this must be set to: USPS** (required)
     * @param  \OpenAPI\Client\Model\ISOCountryCode $origin_country_code The [two-character ISO country code](https://www.iso.org/obp/ui/#search) for the country where the shipment originates. (required)
     * @param  \OpenAPI\Client\Model\ISOCountryCode $destination_country_code The [two-character ISO country code](https://www.iso.org/obp/ui/#search) for the country of the shipment&#39;s destination address. (required)
     * @param  string $x_pb_unified_error_structure Set this to true to use the standard [error object](https://shipping.pitneybowes.com/reference/error-object.html#standard-error-object) if an error occurs. (optional, default to 'true')
     * @param  string $rate_type_id The type of rate requested, such as COMMERCIAL_BASE. If a rate type is not specified, all eligible rate types are returned. (optional)
     * @param  string $future_shipment_date If the shipment is for a future date, and if a rate change is expected before the shipment date, use this field to ensure you get the correct rates and correct rate rules. Note that a rate change can affect the structure of the rate rules as well as the actual rates.Specify this value in UTC/GMT, not in local time. Formats allowed are   * **YYYY-MM-DD**   * **YYYY-MM-DD HH:mm:ss** * **YYYY-MM-DD HH:mm:ss.SSS** (optional)
     * @param  \DateTime $return_shipment If set to true, provides only services applicable for return shipment. (optional)
     * @param  bool $compact_response If set to true, returns only summary, without special service details. (optional)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\CarrierRule|\OpenAPI\Client\Model\Errors
     */
    public function v1InformationRulesRatingServicesGet($accept_language, $carrier, $origin_country_code, $destination_country_code, $x_pb_unified_error_structure = 'true', $rate_type_id = null, $future_shipment_date = null, $return_shipment = null, $compact_response = null)
    {
        list($response) = $this->v1InformationRulesRatingServicesGetWithHttpInfo($accept_language, $carrier, $origin_country_code, $destination_country_code, $x_pb_unified_error_structure, $rate_type_id, $future_shipment_date, $return_shipment, $compact_response);
        return $response;
    }

    /**
     * Operation v1InformationRulesRatingServicesGetWithHttpInfo
     *
     * Retrieves the rules governing the carrier's services.
     *
     * @param  string $accept_language This HTTP header advertises which languages the client is able to understand, and which locale variant is preferred. (required)
     * @param  \OpenAPI\Client\Model\Carrier $carrier The carrier name. **Currently this must be set to: USPS** (required)
     * @param  \OpenAPI\Client\Model\ISOCountryCode $origin_country_code The [two-character ISO country code](https://www.iso.org/obp/ui/#search) for the country where the shipment originates. (required)
     * @param  \OpenAPI\Client\Model\ISOCountryCode $destination_country_code The [two-character ISO country code](https://www.iso.org/obp/ui/#search) for the country of the shipment&#39;s destination address. (required)
     * @param  string $x_pb_unified_error_structure Set this to true to use the standard [error object](https://shipping.pitneybowes.com/reference/error-object.html#standard-error-object) if an error occurs. (optional, default to 'true')
     * @param  string $rate_type_id The type of rate requested, such as COMMERCIAL_BASE. If a rate type is not specified, all eligible rate types are returned. (optional)
     * @param  string $future_shipment_date If the shipment is for a future date, and if a rate change is expected before the shipment date, use this field to ensure you get the correct rates and correct rate rules. Note that a rate change can affect the structure of the rate rules as well as the actual rates.Specify this value in UTC/GMT, not in local time. Formats allowed are   * **YYYY-MM-DD**   * **YYYY-MM-DD HH:mm:ss** * **YYYY-MM-DD HH:mm:ss.SSS** (optional)
     * @param  \DateTime $return_shipment If set to true, provides only services applicable for return shipment. (optional)
     * @param  bool $compact_response If set to true, returns only summary, without special service details. (optional)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\CarrierRule|\OpenAPI\Client\Model\Errors, HTTP status code, HTTP response headers (array of strings)
     */
    public function v1InformationRulesRatingServicesGetWithHttpInfo($accept_language, $carrier, $origin_country_code, $destination_country_code, $x_pb_unified_error_structure = 'true', $rate_type_id = null, $future_shipment_date = null, $return_shipment = null, $compact_response = null)
    {
        $request = $this->v1InformationRulesRatingServicesGetRequest($accept_language, $carrier, $origin_country_code, $destination_country_code, $x_pb_unified_error_structure, $rate_type_id, $future_shipment_date, $return_shipment, $compact_response);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            switch($statusCode) {
                case 200:
                    if ('\OpenAPI\Client\Model\CarrierRule' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\CarrierRule', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                default:
                    if ('\OpenAPI\Client\Model\Errors' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\Errors', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\OpenAPI\Client\Model\CarrierRule';
            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = (string) $responseBody;
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\CarrierRule',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\Errors',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation v1InformationRulesRatingServicesGetAsync
     *
     * Retrieves the rules governing the carrier's services.
     *
     * @param  string $accept_language This HTTP header advertises which languages the client is able to understand, and which locale variant is preferred. (required)
     * @param  \OpenAPI\Client\Model\Carrier $carrier The carrier name. **Currently this must be set to: USPS** (required)
     * @param  \OpenAPI\Client\Model\ISOCountryCode $origin_country_code The [two-character ISO country code](https://www.iso.org/obp/ui/#search) for the country where the shipment originates. (required)
     * @param  \OpenAPI\Client\Model\ISOCountryCode $destination_country_code The [two-character ISO country code](https://www.iso.org/obp/ui/#search) for the country of the shipment&#39;s destination address. (required)
     * @param  string $x_pb_unified_error_structure Set this to true to use the standard [error object](https://shipping.pitneybowes.com/reference/error-object.html#standard-error-object) if an error occurs. (optional, default to 'true')
     * @param  string $rate_type_id The type of rate requested, such as COMMERCIAL_BASE. If a rate type is not specified, all eligible rate types are returned. (optional)
     * @param  string $future_shipment_date If the shipment is for a future date, and if a rate change is expected before the shipment date, use this field to ensure you get the correct rates and correct rate rules. Note that a rate change can affect the structure of the rate rules as well as the actual rates.Specify this value in UTC/GMT, not in local time. Formats allowed are   * **YYYY-MM-DD**   * **YYYY-MM-DD HH:mm:ss** * **YYYY-MM-DD HH:mm:ss.SSS** (optional)
     * @param  \DateTime $return_shipment If set to true, provides only services applicable for return shipment. (optional)
     * @param  bool $compact_response If set to true, returns only summary, without special service details. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1InformationRulesRatingServicesGetAsync($accept_language, $carrier, $origin_country_code, $destination_country_code, $x_pb_unified_error_structure = 'true', $rate_type_id = null, $future_shipment_date = null, $return_shipment = null, $compact_response = null)
    {
        return $this->v1InformationRulesRatingServicesGetAsyncWithHttpInfo($accept_language, $carrier, $origin_country_code, $destination_country_code, $x_pb_unified_error_structure, $rate_type_id, $future_shipment_date, $return_shipment, $compact_response)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v1InformationRulesRatingServicesGetAsyncWithHttpInfo
     *
     * Retrieves the rules governing the carrier's services.
     *
     * @param  string $accept_language This HTTP header advertises which languages the client is able to understand, and which locale variant is preferred. (required)
     * @param  \OpenAPI\Client\Model\Carrier $carrier The carrier name. **Currently this must be set to: USPS** (required)
     * @param  \OpenAPI\Client\Model\ISOCountryCode $origin_country_code The [two-character ISO country code](https://www.iso.org/obp/ui/#search) for the country where the shipment originates. (required)
     * @param  \OpenAPI\Client\Model\ISOCountryCode $destination_country_code The [two-character ISO country code](https://www.iso.org/obp/ui/#search) for the country of the shipment&#39;s destination address. (required)
     * @param  string $x_pb_unified_error_structure Set this to true to use the standard [error object](https://shipping.pitneybowes.com/reference/error-object.html#standard-error-object) if an error occurs. (optional, default to 'true')
     * @param  string $rate_type_id The type of rate requested, such as COMMERCIAL_BASE. If a rate type is not specified, all eligible rate types are returned. (optional)
     * @param  string $future_shipment_date If the shipment is for a future date, and if a rate change is expected before the shipment date, use this field to ensure you get the correct rates and correct rate rules. Note that a rate change can affect the structure of the rate rules as well as the actual rates.Specify this value in UTC/GMT, not in local time. Formats allowed are   * **YYYY-MM-DD**   * **YYYY-MM-DD HH:mm:ss** * **YYYY-MM-DD HH:mm:ss.SSS** (optional)
     * @param  \DateTime $return_shipment If set to true, provides only services applicable for return shipment. (optional)
     * @param  bool $compact_response If set to true, returns only summary, without special service details. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1InformationRulesRatingServicesGetAsyncWithHttpInfo($accept_language, $carrier, $origin_country_code, $destination_country_code, $x_pb_unified_error_structure = 'true', $rate_type_id = null, $future_shipment_date = null, $return_shipment = null, $compact_response = null)
    {
        $returnType = '\OpenAPI\Client\Model\CarrierRule';
        $request = $this->v1InformationRulesRatingServicesGetRequest($accept_language, $carrier, $origin_country_code, $destination_country_code, $x_pb_unified_error_structure, $rate_type_id, $future_shipment_date, $return_shipment, $compact_response);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v1InformationRulesRatingServicesGet'
     *
     * @param  string $accept_language This HTTP header advertises which languages the client is able to understand, and which locale variant is preferred. (required)
     * @param  \OpenAPI\Client\Model\Carrier $carrier The carrier name. **Currently this must be set to: USPS** (required)
     * @param  \OpenAPI\Client\Model\ISOCountryCode $origin_country_code The [two-character ISO country code](https://www.iso.org/obp/ui/#search) for the country where the shipment originates. (required)
     * @param  \OpenAPI\Client\Model\ISOCountryCode $destination_country_code The [two-character ISO country code](https://www.iso.org/obp/ui/#search) for the country of the shipment&#39;s destination address. (required)
     * @param  string $x_pb_unified_error_structure Set this to true to use the standard [error object](https://shipping.pitneybowes.com/reference/error-object.html#standard-error-object) if an error occurs. (optional, default to 'true')
     * @param  string $rate_type_id The type of rate requested, such as COMMERCIAL_BASE. If a rate type is not specified, all eligible rate types are returned. (optional)
     * @param  string $future_shipment_date If the shipment is for a future date, and if a rate change is expected before the shipment date, use this field to ensure you get the correct rates and correct rate rules. Note that a rate change can affect the structure of the rate rules as well as the actual rates.Specify this value in UTC/GMT, not in local time. Formats allowed are   * **YYYY-MM-DD**   * **YYYY-MM-DD HH:mm:ss** * **YYYY-MM-DD HH:mm:ss.SSS** (optional)
     * @param  \DateTime $return_shipment If set to true, provides only services applicable for return shipment. (optional)
     * @param  bool $compact_response If set to true, returns only summary, without special service details. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function v1InformationRulesRatingServicesGetRequest($accept_language, $carrier, $origin_country_code, $destination_country_code, $x_pb_unified_error_structure = 'true', $rate_type_id = null, $future_shipment_date = null, $return_shipment = null, $compact_response = null)
    {
        // verify the required parameter 'accept_language' is set
        if ($accept_language === null || (is_array($accept_language) && count($accept_language) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $accept_language when calling v1InformationRulesRatingServicesGet'
            );
        }
        // verify the required parameter 'carrier' is set
        if ($carrier === null || (is_array($carrier) && count($carrier) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $carrier when calling v1InformationRulesRatingServicesGet'
            );
        }
        // verify the required parameter 'origin_country_code' is set
        if ($origin_country_code === null || (is_array($origin_country_code) && count($origin_country_code) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $origin_country_code when calling v1InformationRulesRatingServicesGet'
            );
        }
        // verify the required parameter 'destination_country_code' is set
        if ($destination_country_code === null || (is_array($destination_country_code) && count($destination_country_code) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $destination_country_code when calling v1InformationRulesRatingServicesGet'
            );
        }

        $resourcePath = '/v1/information/rules/rating-services';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($carrier !== null) {
            if('form' === 'form' && is_array($carrier)) {
                foreach($carrier as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['carrier'] = $carrier;
            }
        }
        // query params
        if ($origin_country_code !== null) {
            if('form' === 'form' && is_array($origin_country_code)) {
                foreach($origin_country_code as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['originCountryCode'] = $origin_country_code;
            }
        }
        // query params
        if ($destination_country_code !== null) {
            if('form' === 'form' && is_array($destination_country_code)) {
                foreach($destination_country_code as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['destinationCountryCode'] = $destination_country_code;
            }
        }
        // query params
        if ($rate_type_id !== null) {
            if('form' === 'form' && is_array($rate_type_id)) {
                foreach($rate_type_id as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['rateTypeId'] = $rate_type_id;
            }
        }
        // query params
        if ($future_shipment_date !== null) {
            if('form' === 'form' && is_array($future_shipment_date)) {
                foreach($future_shipment_date as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['futureShipmentDate'] = $future_shipment_date;
            }
        }
        // query params
        if ($return_shipment !== null) {
            if('form' === 'form' && is_array($return_shipment)) {
                foreach($return_shipment as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['returnShipment'] = $return_shipment;
            }
        }
        // query params
        if ($compact_response !== null) {
            if('form' === 'form' && is_array($compact_response)) {
                foreach($compact_response as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['compactResponse'] = $compact_response;
            }
        }

        // header params
        if ($accept_language !== null) {
            $headerParams['Accept-Language'] = ObjectSerializer::toHeaderValue($accept_language);
        }
        // header params
        if ($x_pb_unified_error_structure !== null) {
            $headerParams['X-PB-UnifiedErrorStructure'] = ObjectSerializer::toHeaderValue($x_pb_unified_error_structure);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($_tempBody));
            } else {
                $httpBody = $_tempBody;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
