<?php
/**
 * CarrierInfoApiTest
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Shipping API
 *
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * CarrierInfoApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CarrierInfoApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for v1CarrierFacilityPost
     *
     * Find Carrier Facilities.
     *
     */
    public function testV1CarrierFacilityPost()
    {
    }

    /**
     * Test case for v1CarrierLicenseAgreementsGet
     *
     * This operation retrieves a carrier's license agreement..
     *
     */
    public function testV1CarrierLicenseAgreementsGet()
    {
    }

    /**
     * Test case for v1CountriesGet
     *
     * This operation returns a list of supported destination countries to which the carrier offers international shipping services..
     *
     */
    public function testV1CountriesGet()
    {
    }

    /**
     * Test case for v1InformationRulesRatingServicesGet
     *
     * Retrieves the rules governing the carrier's services..
     *
     */
    public function testV1InformationRulesRatingServicesGet()
    {
    }
}
